name: osm_overpass
description: A dart package to query the OpenStreetMap Overpass API.
version: 0.0.1
repository: https://github.com/danemadsen/osm_overpass

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  latlong2: ^0.9.1

dev_dependencies:
  lints: ^4.0.0

